### ISSUE TITLE
4.4.2 release?

### ISSUE THREAD

**Issue by caiobsilva** [oVirt/ovirt-engine-sdk-ruby#4]
I'm having some issues upgrading an application I'm working on to Ruby 3.2.0:
```
An error occurred while installing ovirt-engine-sdk (4.4.1), and Bundler cannot continue.

In Gemfile:
  fog was resolved to 2.3.0, which depends on
    fog-ovirt was resolved to 2.0.2, which depends on
      ovirt-engine-sdk
```

That is due to a deprecated call on the gem:
```
ov_http_request.c:347:77: error: ‘rb_cData’ undeclared (first use in this function)
  347 |     ov_http_request_class = rb_define_class_under(ov_module, "HttpRequest", rb_cData);
```

I see that this is fixed on #3, but the last update on RubyGems is dated from February 23, 2021. Are there any plans to update the package in there? Can I do something to help?

**Comment by michalskrivanek** [comment]
ruby sdk is not actively developed anymore. We used to use it internally for integration with manageiq but we've stopped that few years ago and since then there were not many users for sdk

I don't know what it takes to update it TBH, @oliel is it easy enough to just release current master?

**Comment by caiobsilva** [comment]
It seems to me that the master branch already has the needed changes. You would just have to release it as a package, and it would be greatly appreciated :raised_hands:

**Comment by mwperina** [comment]
Gui is the only Ruby SDK maintainer at the moment, he is the only who has required knowledge.

@santos1709

**Comment by tkriplean** [comment]
Thanks for reporting this, I'm experiencing this exact same bug while installing the backup gem on Ruby 3.2.0.

**Comment by afilbert** [comment]
I was able to get 4.4.1 to install with the following:

```
gem install ovirt-engine-sdk:4.4.1 -- --with-cflags=-Drb_cData=rb_cObject
```

**Comment by alemata** [comment]
Hello! Any update on this? This is blocking updating to ruby 3.2.0

**Comment by caiobsilva** [comment]
I've since opted to drop the `fog` gem from my project, instead using fog-aws. Relevant issue on the fog repo: https://github.com/fog/fog/issues/4034

**Comment by tomash** [comment]
Ping on this one, it's blocking `backup` gem from supporting anything newer than Ruby 3.1.4.

**Comment by hoenth** [comment]
I was able to install the gem by adding the following to my .bundle/config file:
```
BUNDLE_BUILD__OVIRT___ENGINE___SDK: "--with-cflags=-Drb_cData=rb_cObject"
```

**Comment by ekohl** [comment]
> ruby sdk is not actively developed anymore. We used to use it internally for integration with manageiq but we've stopped that few years ago and since then there were not many users for sdk

Foreman (and thus Satellite) also uses this gem. We're a bit slow to update our Ruby version, but if there's no new release then we will drop oVirt support.

**Comment by fraenki** [comment]
@mwperina @ sandrobonazzola @santos1709 Since the fix is already merged (#3), could anyone **please** issue release 4.4.2? It's probably not a big deal and would **tremendously** help folks that are still using oVirt. **Thanks** :smiling_face_with_tear:

**Comment by mwperina** [comment]
I've tried resurrect CI and provide necessary fixes to do a release, so here is a new release: https://github.com/oVirt/ovirt-engine-sdk-ruby/releases/tag/4.6.0
But we don't have anyone in the former oVirt team with Ruby knowledge, so I cannot verify if the release works fine.
Also this version is not yet uploaded to rubygems.org, trying to get required permissions.

**Comment by mwperina** [comment]
oVirt Ruby SDK 4.6.0 was released to rubygems.org: https://rubygems.org/gems/ovirt-engine-sdk/versions/4.6.0

**Comment by fraenki** [comment]
@mwperina **THANK YOU!** :+1: Much appreciated. :smile:
